### ISSUE TITLE
Missing tax rate term

### ISSUE THREAD

**Issue by Matthew-Boyd** [watertap-org/watertap-reflo#19]
https://github.com/watertap-org/watertap-seto/blob/77b555a87fb6829bfece7a9e414b44910834e2d4/src/watertap_contrib/seto/costing/solar/photovoltaic.py#L157-L159

E.g.,
![image](https://user-images.githubusercontent.com/30417543/215235143-667f4210-5a08-4e0b-adad-b90ef73796b9.png)

**Comment by kurbansitterley** [comment]
Thanks for catching this. I think I excluded this from the initial costing model because I wasn't sure if we handled sales tax at the system level (rather than the unit level). But then I didn't circle back to it. I will add this in a future PR.

**Comment by adam-a-a** [comment]
Actually, shouldn't this be at the system level (in most cases)?

**Comment by kurbansitterley** [comment]
tax rate was made a global costing param long long ago...
