### ISSUE TITLE
Add copyright header to all files

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap-reflo#24]
Since this is going to be a WaterTAP "add-in," can we get by in the interim with the WaterTAP copyright header?

**Comment by kurbansitterley** [comment]
I have been including it but I don't know the answer to this question.

**Comment by adam-a-a** [comment]
@kurbansitterley is going to talk with @bknueven to figure out who to ask about this so that we can settle the issue.

**Comment by kurbansitterley** [comment]
Addressed with #91
