### ISSUE TITLE
Development of multiperiod model for VAGMD-batch

### ISSUE THREAD

**Issue by Zhuoran29** [watertap-org/watertap-reflo#42]
There's a list to complete the whole multiperiod model:

- [x] Implement the steady-state unit model
- [x] Implement the multiperiod model based on the unit model, and create test flowsheet
- [x] Refine unit model as needed
- [x] Refine flowsheet as needed
- [x] Develop surrogate equations for estimating the number of recirculations needed
- [x] Add documentation for steady-state model 
- [x] Add documentation for the flowsheet example and workflow of a multiperiod model

**Comment by kurbansitterley** [comment]
@Zhuoran29 @adam-a-a will this be taken care of with #113?

**Comment by Zhuoran29** [comment]
@kurbansitterley Ah, this issue was created to track the development progress of MD model, and should be resolved when #83 was merged. Sorry about the confusion and I'll close it with this comment.

#113 is a modification of #83, in order to reform the multiperiod structure from a unit model to a flowsheet object.
