### ISSUE TITLE
Add multiperiod model demo as a first tutorial on REFLO!

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap-reflo#80]
I created an issue on WaterTAP main, which included @zacharybinger 's code demo in the list, but that demo probably fits best in this repo and can serve as our initial tutorial for WaterTAP-REFLO. The original issue is referenced below:

https://github.com/watertap-org/watertap/issues/1173#issue-1945824433

**Comment by kurbansitterley** [comment]
this should be addressed by #92
