### ISSUE TITLE
Issues with trough surrogate test

### ISSUE THREAD

**Issue by kurbansitterley** [watertap-org/watertap-reflo#95]
Creating issue to track trough surrogate test failures.

I am sometimes getting tests passing locally and sometimes not. This may be as close as we can get to duplicating the issue 84. 

Here the tests passed and then I separated the large and small tests into separate classes (didn't modify tests) and ran the tests again and didn't get test failures, but some other failure that caused pytest to stop and was indicated by the ``%`` symbol at the end of the pytest output.

![Screenshot 2023-12-22 at 4 39 41 PM](https://github.com/watertap-org/watertap-reflo/assets/49287860/531ec425-8f32-4689-a060-62de5aba8401)

**Comment by kurbansitterley** [comment]
running trough tests locally _outside_ of pytest several times in a row. ``test_create_rbf_surrogate_large`` failed on 6th iteration. Values for ``m.fs.trough.electricity`` were: 

```
700.0214395365647,
725.6052369525075,
713.5508137417017,
732.7247181584798,
708.4853938896426
```

Locally I added a solution test after solving: 

```
m.fs.trough.heat_load.fix(200)
m.fs.trough.hours_storage.fix(4)
m.fs.trough.initialize()
results = solver.solve(m)
```

which gave these results:

```
trough_results = {'electricity': 727.242,
                                 'heat': 93885.264,
                                 'heat_load': 200.0,
                                 'hours_storage': 4.0,
                                 'heat_annual_scaled': 0.31056777,
                                 'electricity_annual_scaled': 0.048634913,
                                 'heat_annual': 822998231.988,
                                 'electricity_annual': 6375009.402}
```

Testing these results against that setup in pytest failed with tol=1e-2, but pass with tol=0.1

**Comment by kurbansitterley** [comment]
Not using ``initialization_tester`` maybe helps? Instead using ``m.fs.trough.initialize()``

**Comment by kurbansitterley** [comment]
After playing with the trough surrogate tests for a while, it seems it doesn't solve consistently. When running the tests outside pytest locally several times in a row, would get failures in tests creating RBF surrogate, validation, and costing. 

So I reverted back to skipping the trough tests for now in #91. 


@dguittet @adam-a-a just tagging for visibility

**Comment by adam-a-a** [comment]
Potential approaches to resolve: 
(1) Try to control randomness via training step to see if we can eliminate randomness in solutions (e.g., setting something like random.seed(1000) would set same sequence of random numbers)
(2) use a very small dataset so that deviations will be minimal.
