### ISSUE TITLE
Costing MgCl2 flow in chemical softening

### ISSUE THREAD

**Issue by kurbansitterley** [watertap-org/watertap-reflo#97]
After updating to watertap 11, there is an error in costing MgCl2 flow with Expr_if constraints. 
Will update with more info.

**Comment by kurbansitterley** [comment]
Opened [Pyomo issue 3083](https://github.com/Pyomo/pyomo/issues/3083).

**Comment by zacharybinger** [comment]
Maybe the method used in Darice's fixes to the PV costing from commit [f37dc79](https://github.com/dguittet/watertap-seto/commit/f37dc797116d916c9d0dbfdb9780e03071f1dcd7)

**Comment by kurbansitterley** [comment]
Should be handled with #119
